AlytaloMVC/Controllers/HallintaController.cs
using AlytaloMVC.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlytaloMVC.Controllers
{
    public class HallintaController : Controller
    {
        public bool OK { get; private set; }

        // GET: Hallinta
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetSauna()
        {
            AlyTaloEntities entities = new AlyTaloEntities();
            var model = (from v in entities.Sauna
                         select new
                         {
                             v.SaunaID,
                             v.Sauna_Nimi

                         }).ToList();

            string json = JsonConvert.SerializeObject(model);
            entities.Dispose();
            Response.Expires = - 1;

            return Json(json, JsonRequestBehavior.AllowGet);
         
        }

        public ActionResult NewSauna(Sauna pro)
        {
            AlyTaloEntities entities = new AlyTaloEntities();
            int id = pro.SaunaID;

            bool OK = false;

            if (pro.SaunaID == 0)

            {

                // kyseessä on uuden asiakkaan lisääminen, kopioidaan kentät
                Sauna dbItem = new Sauna()
                {
                    SaunaID = pro.SaunaID,
                    Sauna_Nimi = pro.Sauna_Nimi,

                };

                // tallennus tietokantaan
                entities.Sauna.Add(dbItem);
                entities.SaveChanges();
                OK = true;
                
            }
            ModelState.Clear();
            entities.Dispose();
            return Json(OK, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Delete(Sauna pro)
        {
            AlyTaloEntities entities = new AlyTaloEntities();
            //haetaan id:n perusteella rivi SQL tietokannasta

            Sauna dbItem = (from p in entities.Sauna
                                    where p.SaunaID == pro.SaunaID
                                    select p).FirstOrDefault();
            {
                // tietokannasta poisto
                entities.Sauna.Remove(dbItem);
                entities.SaveChanges();
                OK = true;
            }
            entities.Dispose();

            return Json(OK, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetValot()
        {
            AlyTaloEntities entities = new AlyTaloEntities();
            var model = (from v in entities.Valot
                         select new
                         {
                             v.ValoID,
                             v.Huone

                         }).ToList();

            string json = JsonConvert.SerializeObject(model);
            entities.Dispose();
            Response.Expires = -1;

            return Json(json, JsonRequestBehavior.AllowGet);

        }

        public ActionResult NewValot(Valot pro)
        {
            AlyTaloEntities entities = new AlyTaloEntities();
            int id = pro.ValoID;

            bool OK = false;

            if (pro.ValoID == 0)

            {

                // kyseessä on uuden asiakkaan lisääminen, kopioidaan kentät
                Valot dbItem = new Valot()
                {
                    ValoID = pro.ValoID,
                    Huone = pro.Huone,

                };

                // tallennus tietokantaan
                entities.Valot.Add(dbItem);
                entities.SaveChanges();
                OK = true;

            }
            ModelState.Clear();
            entities.Dispose();
            return Json(OK, JsonRequestBehavior.AllowGet);

        }

        public ActionResult DeleteValot(Valot pro)
        {
            AlyTaloEntities entities = new AlyTaloEntities();
            //haetaan id:n perusteella rivi SQL tietokannasta

            Valot dbItem = (from p in entities.Valot
                            where p.ValoID == pro.ValoID
                            select p).FirstOrDefault();

            {
                // tietokannasta poisto
                entities.Valot.Remove(dbItem);
                entities.SaveChanges();
                OK = true;
            }
            entities.Dispose();

            return Json(OK, JsonRequestBehavior.AllowGet);
        }
    }
}

AlytaloMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlytaloMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AlytaloMVC/Controllers/LampoTilaController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlytaloMVC.Models
{
    public class LampoTilaController : Controller
    {
        public bool OK { get; private set; }
        public string ErrorMessage { get; private set; }


        // GET: LampoTila
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetList()
        {
            AlyTaloEntities entities = new AlyTaloEntities();
            var model = (from p in entities.HuoneLampotila
                         select new
                         {
                             p.HuoneID,
                             p.HuoneenNimi,
                             p.Lampotila

                         }).ToList();

            string json = JsonConvert.SerializeObject(model);
            entities.Dispose();
            //välimuistin hallinta
            Response.Expires = -1;
            Response.CacheControl = "no-cache";

            return Json(json, JsonRequestBehavior.AllowGet);
        }


        public ActionResult LampoMiinus(string id)
        {
            AlyTaloEntities entities = new AlyTaloEntities();

            bool OK = false;
            HuoneLampotila dbItem = (from p in entities.HuoneLampotila
                                     where p.HuoneID.ToString() == id
                                     select p).FirstOrDefault();

            if (dbItem != null)
            {
                dbItem.Lampotila = dbItem.Lampotila - 1;

                if ( dbItem.Lampotila > 17 && dbItem.Lampotila < 25)

                    
                        entities.SaveChanges();
                        OK = true;
                    

            }
            //entiteettiolion vapauttaminen
            entities.Dispose();

      
            // palautetaan 'json' muodossa
            return Json(OK, JsonRequestBehavior.AllowGet);



        }
        public ActionResult LampoPlus(string id)
        {
            AlyTaloEntities entities = new AlyTaloEntities();

            bool OK = false;
            HuoneLampotila dbItem = (from p in entities.HuoneLampotila
                                     where p.HuoneID.ToString() == id
                                     orderby p.HuoneID descending
                                     select p).FirstOrDefault();

            if (dbItem != null)
            {
                dbItem.Lampotila = dbItem.Lampotila + 1;

                if (dbItem.Lampotila > 17 && dbItem.Lampotila < 25)

                {
                    entities.SaveChanges();
                    OK = true;
                }

            }
            //entiteettiolion vapauttaminen
            entities.Dispose();


            // palautetaan 'json' muodossa
            return Json(OK, JsonRequestBehavior.AllowGet);



        }
    }
}

AlytaloMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AlytaloMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AlytaloMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
    .li {
        font-family: 'Lucida Console';
        font-size: 20px;
        color:rgb(0,0,225);
    }

</style>
<div class="container text-center" style="background-color:rgba(250,250,250,0.5); margin-top:100px; margin-bottom:200px;">
    <h1>My ÄlyTalo App</h1>
    <p class="lead">Lisää tarvittaessa tiloja, tai poista tiloja. Hallitse lämpötiloja, tai laita sauna päälle</p>
    <ul>
        <li class="li">@Html.ActionLink("Hallitse tiloja", "Index", "Hallinta")</li>
        <li class="li">@Html.ActionLink("Valot", "Index", "Valot")</li>
        <li class="li">@Html.ActionLink("Sauna", "Index", "Sauna")</li>
        <li class="li">@Html.ActionLink("Lämmönsäätö", "Index", "LampoTila")</li>
    </ul>
</div>